In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 1.9 MB/s eta 0:00:07
   ----- ---------------------------------- 1.6/12.6 MB 3.1 MB/s eta 0:00:04
   ------- -------------------------------- 2.4/12.6 MB 3.2 MB/s eta 0:00:04
   ----------- ---------------------------- 3.7/12.6 MB 3.9 MB/s eta 0:00:03
   --------------- ------------------------ 5.0/12.6 MB 4.3 MB/s eta 0:00:02
   ---------------- ----------------------- 5.2/12.6 MB 4.3 MB/s eta 0:00:02
   ------------------ --------------------- 5.8/12.6 MB 3.6 MB/s eta 0:00:02
   ------------------------ --------------- 7.6/12.6 MB 4.2 MB/s eta 0:00:02
   ----------------------------- ---------- 9.2/12.6 MB 4.4 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.6 MB 4.6 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 4.6 MB/s eta 0:00:01
   --------

In [3]:
import numpy as np

In [3]:
print(np.__version__)

2.5.0


In [4]:
## 1. Creating arrays

In [5]:
list1=[1,2,3]
print(list1)

[1, 2, 3]


In [7]:
arr_list1=np.array(list1)
print(arr_list1)

[1 2 3]


In [9]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [10]:
list1=[1,2,3]
list2=[4,5,6]
arr_list1_2=np.array([list1,list2])
print(arr_list1_2)

[[1 2 3]
 [4 5 6]]


In [13]:
print(arr_list1_2.ndim)

2


In [11]:
list1=[1,2,3]
list2=[4,5,6]
list3=[7,8,9]
arr_list=np.array([[list1,list2,list3]])
print(arr_list)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [12]:
print(arr_list.ndim)

3


In [15]:
#2. Numpy array attributes

In [23]:
arr2d=np.array([[1,2,3],[4,5,6]])
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [24]:
print("Shape",arr2d.shape)
print("Size",arr2d.size)
print("dType",arr2d.dtype)
print("n_dim",arr2d.ndim)

Shape (2, 3)
Size 6
dType int64
n_dim 2


In [19]:
#Create 2 array - 1D and 3D, and find it's attributes

In [25]:
arr1d=np.array([1,2,3])
print(arr1d) #[1,2,3]
print("Shape",arr1d.shape) #Shape (3)
print("Size",arr1d.size)#3
print("dType",arr1d.dtype) # int 64
print("n_dim",arr1d.ndim) #1

[1 2 3]
Shape (3,)
Size 3
dType int64
n_dim 1


In [30]:
arr3d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3d)#[[[1,2,3],[4,5,6],[7,8,9]]]]

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [32]:
print("Shape",arr3d.shape)#(1,3,3)
print("Size",arr3d.size)#9
print("dType",arr3d.dtype)#int 64
print("n_dim",arr3d.ndim)#3

Shape (1, 3, 3)
Size 9
dType int64
n_dim 3


In [1]:
#3. Array initialization methods

In [4]:
# zero array
zero_arr=np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# one array
one_arr=np.ones((2,3))
print(one_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
#Full Array
full_arr=np.full((3,2),9)
print(full_arr)

[[9 9]
 [9 9]
 [9 9]]


In [12]:
# Identity Matrix only 3 x 3
id_arr=np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
# empty Array
print(np.empty(2))

[7.49914152e-312 7.49888639e-312]


In [16]:
# Evenlly spaced array
print(np.arange(1,4,1))

[1 2 3]


In [20]:
#specific number of equally(spaced) b/w a range
print(np.linspace(1,10,4))

[ 1.  4.  7. 10.]


In [22]:
#random values array -float
r_arr=np.random.rand(3,2)
print(r_arr)

[[0.95321632 0.00203822]
 [0.62776653 0.77538453]
 [0.26560622 0.72987908]]


In [25]:
#random values array -int
r_arr=np.random.randint(1,10,(3,3))
print(r_arr)

[[2 5 7]
 [2 1 5]
 [3 6 3]]


In [32]:
# Array indexing and slicing array[start:stop:step]

In [33]:
a=np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [34]:
print(a[0:2])

[1 3]


In [35]:
print(a[-3:-1])

[5 7]


In [37]:
print(a[0:5:2])

[1 5 9]


In [38]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [43]:
print(arr2[0])
print(arr2[1])

[1 2 3]
[4 5 6]


In [44]:
print(arr2[0][0])

1


In [45]:
print(arr2[1][2])

6


In [49]:
print(arr2[1:])

[[4 5 6]]


In [50]:
print(arr2[0:])

[[1 2 3]
 [4 5 6]]


In [51]:
print(arr2[:])

[[1 2 3]
 [4 5 6]]


In [55]:
#2D arr2[row:columns]
#3D [layers/heights,rows,columns]

In [56]:
print(arr2[:,2])

[3 6]


In [4]:
arr3=np.array([
               [1,2,3],
               [4,5,6],
               [7,8,9]
              ])
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print(arr3[0])
print(arr3[1])
print(arr3[2])
print(arr3.ndim)

[1 2 3]
[4 5 6]
[7 8 9]
2


In [6]:
print(arr3[0][2])

3


In [7]:
print(arr3[0][2])
print(arr3[2][2])

3
9


In [8]:
print(arr3[:,0])
print(arr3[:,1])
print(arr3[:,2])

[1 4 7]
[2 5 8]
[3 6 9]


In [9]:
print(arr3[::2,0])

[1 7]


In [10]:
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(arr3[::,1:2])

[[2]
 [5]
 [8]]


In [12]:
print(arr3[1::,1:2])

[[5]
 [8]]


In [13]:
#Array Reshapping and Flattening

In [16]:
arr1=np.array([1,2,3,4,5,5])
print(arr1)

[1 2 3 4 5 5]


In [18]:
reshaped=arr1.reshape(6,1)
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [5]]


In [20]:
reshaped2=arr1.reshape(2,3)
print(reshaped2)

[[1 2 3]
 [4 5 5]]


In [25]:
flatting=reshaped2.flatten()
print(flatting)

[1 2 3 4 5 5]


In [26]:
# Array Stacking and splitting

In [30]:
a=np.array([1,2,3])
b=np.array([4,5,6])

print(np.vstack((a,b))) # Vertical stacking -row wise
print(np.hstack((a,b))) # Horizontal Stacking -column wise

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [32]:
c=np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [36]:
split=np.hsplit(c,3) #horizontal split
for s in split:
    print(s)

[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [39]:
split=np.vsplit(c,2)#Vertical Split
for h in split:
    print(h)

[[1 2 3]]
[[4 5 6]]


In [40]:
# Mathematical Operation on Array

In [42]:
a=np.array([10,20,40,-30])
print(a)

[ 10  20  40 -30]


In [44]:
print(a+10) # Add
print(a-30) #Substract
print(a*2) #Multiply
print(a/10) #Divide

[ 20  30  50 -20]
[-20 -10  10 -60]
[ 20  40  80 -60]
[ 1.  2.  4. -3.]


In [45]:
b=np.array([1,4,9])
print(b)

[1 4 9]


In [46]:
print(np.square(b))
print(np.sqrt(b))

[ 1 16 81]
[1. 2. 3.]


In [48]:
#HW ---> Sin,tan,cos

In [49]:
# Mathemical Operations on Multiple Arrays

In [50]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [51]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [53]:
print(np.dot(a,b)) #dot product

32


In [54]:
print(a.T)#Transpose

[1 2 3]


In [57]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [58]:
# Statistical Functions

In [59]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [60]:
print(np.sum(a))

21


In [63]:
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))

3.5
3.5
1.707825127659933
1
6


In [64]:
# Array Comparison

In [67]:
a=np.array([1,5,3])
b=np.array([4,5,6])
print(a)
print(b)

[1 5 3]
[4 5 6]


In [69]:
print(a==b)# Comparing each elements
print(np.array_equal(a,b)) #Cmparing complete array

[False  True False]
False


In [70]:
#Broadcasting

In [71]:
a=np.array([1,2,3,4])
b=np.array([5])
print(a+b)

[6 7 8 9]


In [74]:
c=np.array([[1,2,3],[4,5,6]])
d=np.array([10,20,30])
print(c+d)

[[11 22 33]
 [14 25 36]]


In [77]:
# Handling with nan & inf

In [78]:
data1=np.array([1,2,np.nan,4,np.inf])
print(data1)

[ 1.  2. nan  4. inf]


In [79]:
print(np.isnan(data1))

[False False  True False False]


In [80]:
print(np.isinf(data1))

[False False False False  True]


In [81]:
print(np.nan_to_num(data1))

[1.00000000e+000 2.00000000e+000 0.00000000e+000 4.00000000e+000
 1.79769313e+308]


In [82]:
#save and load arrays

In [83]:
arr=np.array([1,0,0,8])
print(arr)
np.save('my_array.npy',arr)

[1 0 0 8]


In [84]:
loaded_arr=np.load('my_array.npy')
print(loaded_arr)

[1 0 0 8]


In [85]:
#Homewor
# Create 5x5 matrix with values from 1 to 25
# extract last row, first column, mub matrix containing 3x3

#Broadcasting: multiply shape(3,1) matriz with shape(3,)

In [5]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(arr)
print(arr.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
2


In [6]:
print(arr[4])#Last Row

[21 22 23 24 25]


In [15]:
print(arr[0:5,0]) # First Column

[ 1  6 11 16 21]


In [17]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
#mub matrix containing 3x3
print(arr*arr1)

ValueError: operands could not be broadcast together with shapes (5,5) (3,3) 