In [1]:
# Install Numpy
!pip install numpy

In [1]:
# Import Numpy library
import numpy as np

In [3]:
print(np.__version__)# Numpy version installed in the system

2.5.0


In [4]:
# 1. creating arrays

In [5]:
list1=[1,2,3]
print(list1)

[1, 2, 3]


In [7]:
arr_list1=np.array(list1) # creating array using list
print(arr_list1)

[1 2 3]


In [9]:
print(type(arr_list1))# check data type of variable

<class 'numpy.ndarray'>


In [10]:
# creating 2-dim array using 2 lists
list1=[1,2,3]
list2=[4,5,6]
arr_list2=np.array([list1,list2])
print(arr_list2)

[[1 2 3]
 [4 5 6]]


In [11]:
print(arr_list2.ndim)# check dimension of array

2


In [15]:
# creating 3-dim array using 3 lists
list1=[1,2,3]
list2=[4,5,6]
list3=[7,8,9]
arr_list_3=np.array([[list1,list2,list3]])
print(arr_list_3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [16]:
print(arr_list_3.ndim) # check dimension of array

3


In [17]:
# 2. numpy array attributes

In [18]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [20]:
# Attributes of Array (properties of array)
print("Shape",arr1.shape)# share= rows, columns and height of array
print("Size",arr1.size) # number of elements in array
print("dType",arr1.dtype) # data type of elements in array
print("n_dim",arr1.ndim)  # dimension of array

Shape (2, 3)
Size 6
dType int64
n_dim 2


In [21]:
#1D
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [23]:
# Attributes of Array (properties of array)
print("Shape",arr.shape) # share= rows, columns and height of array
print("Size",arr.size) # number of elements in array
print("dType",arr.dtype) # data type of elements in array
print("n_dim",arr.ndim)   # dimension of array

Shape (3,)
Size 3
dType int64
n_dim 1


In [24]:
#3D Array
arr_3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr_3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [25]:
# Attributes of Array (properties of array)
print("Shape",arr_3.shape) # share= rows, columns and height of array
print("Size",arr_3.size) # number of elements in array
print("dType",arr_3.dtype)  # data type of elements in array
print("n_dim",arr_3.ndim)  # dimension of array

Shape (1, 3, 3)
Size 9
dType int64
n_dim 3


In [26]:
# 3. Array initialization methods

In [27]:
# zeros array : all elements are 0
zero_arr=np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [28]:
# ones array : all elements are 1
one_arr=np.ones((1,3))
print(one_arr)

[[1. 1. 1.]]


In [29]:
# Full array : all elements are same based on given value
full_arr=np.full((3,2),9)
print(full_arr)

[[9 9]
 [9 9]
 [9 9]]


In [30]:
# Identity Matrix : diagonal elements are ones and all other elements are zeros
id_arr=np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
# empty array
empty_arr=np.empty(2)
print(empty_arr)

[3.32234062e+257 1.10593219e-311]


In [32]:
# evenly spaced array : elements are evenly spaced based on step value
print(np.arange(2,10,2))

[2 4 6 8]


In [33]:
# specific number of eqaully spaced values between a range : elements are equally spaced based on step value
print(np.linspace(1,10,4))

[ 1.  4.  7. 10.]


In [34]:
# random values array - float
r_arr=np.random.rand(3,2)
print(r_arr)

[[0.26010187 0.23230647]
 [0.74251919 0.08520566]
 [0.10709886 0.92273796]]


In [36]:
# random values array - int
rint_arr=np.random.randint(1,100,(3,3))
print(rint_arr)

[[57 82 62]
 [40 75 51]
 [19 75 33]]


In [37]:
# 4 Array Indexing and Slicing

In [38]:
a=np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [39]:
print(a[0])# first element of array
print(a[4])# fifth element of array
print(a[-1])# last element of array

1
9
9


In [41]:
a=np.array([1,3,5,7,9])
print(a)
# Slicing :
# array[start:stop:step]
# stop - index, that is not included in output

[1 3 5 7 9]


In [42]:
print(a[0:3]) # First 3 elements
print(a[-3:]) # Last 3 elements

[1 3 5]
[5 7 9]


In [43]:
print(a[1:4]) # Middle 3 elements
print(a[0:3]) # Middle 3 elements with steps
print(a[0::2]) # All alternative elements with steps

[3 5 7]
[1 3 5]
[1 5 9]


In [44]:
# Indexing on 2 Dimensional Array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
# 2D Array: [rows, columns]                   # 2D Array takes 2 values - rows and columns for indexing
# 3D Array: [layers/height, rows, columns]    # 3D Array takes 3 values - height, rows and columns for indexing

[[1 2 3]
 [4 5 6]]


In [45]:
print(arr2[0]) # first row
print(arr2[1]) # second row

[1 2 3]
[4 5 6]


In [46]:
# Slicing on 2D array
print(arr2[0][0]) # element of first row and first column
print(arr2[0][1]) # element of first row and second column
print(arr2[1][2]) # element of second row and third column

1
2
6


In [47]:
print(arr2[1]) # specific element - 1D
print(arr2[1:]) # slicing part - 2D

[4 5 6]
[[4 5 6]]


In [48]:
print(arr2)
# 2D Array: [rows, columns]  |  eg: arr2[0][1]     # 2D Array takes 2 values - rows and columns for indexing

[[1 2 3]
 [4 5 6]]


In [49]:
print(arr2[:,0])# First column of an array
print(arr2[:,1])     # Second column of an array
print(arr2[:,2])# Third column of an array

[1 4]
[2 5]
[3 6]


In [50]:
arr3=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr3)
# 3D Array: [layers/height, rows, columns]        # 3D Array takes 3 values - height, rows and columns for indexing

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
print(arr3[0])
print(arr3[1])
print(arr3[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [52]:
print(arr3[0][2])
print(arr3[2][2])

3
9


In [53]:
print(arr3[:,0]) # 1st col value
print(arr3[:,1]) # 2nd col value
print(arr3[:,2]) # 3rd col value

[1 4 7]
[2 5 8]
[3 6 9]


In [55]:
print(arr3[::,1:2]) #slicing on columns
print(arr3[2::,1:2]) #slicing on rows and columns

[[2]
 [5]
 [8]]
[[8]]


In [56]:
# 5 Array Reshaping and Flattening

In [57]:
# Reshape Array: changing its dimensions (e.g., rows and columns) without altering the actual data
# Flatten Array: transforming a multi-dimensional array into a single-dimensional array

In [58]:
arr1=np.array([1,2,3,4,5,6])# shape = (1,6) - 1 row and 6 columns
print(arr1)

[1 2 3 4 5 6]


In [59]:
reshaped=arr1.reshape((6,1))
print(reshaped)# shape = (6,1) - 6 rows and 1 column

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [61]:
reshaped2=arr1.reshape((2,3))# re-shaped array from (1,6) to (2,3)
print(reshaped2)

[[1 2 3]
 [4 5 6]]


In [62]:
print(reshaped2.flatten())# flattened array from higher (2D) dimensional (2,3) to (1,6) (1D)

[1 2 3 4 5 6]


In [63]:
#6 Array Stacking and Splitting

In [64]:
# Array Stacking:  combining multiple arrays along a new axis, resulting in an array with a higher dimension than the input arrays
# Array Splitting:

In [66]:
# stacking
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.vstack((a,b))) # vertical stacking - row wise          -> output array is 2D
print(np.hstack((a,b))) # horizontal stacking - column wise     -> output array is 1D

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [67]:
# splitting
c=np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [68]:
hsplit=np.hsplit(c,3)# horizontal split -> input and output array are same dimention

for s in hsplit:
    print(s)

[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [69]:
vsplit=np.vsplit(c,2)# vertical split -> input and output array are same dimention

for s in vsplit:
    print(s)

[[1 2 3]]
[[4 5 6]]


In [3]:
# 7 Mathematical Operations on Array

In [2]:
a=np.array([10,20,40,-30])
print(a)

[ 10  20  40 -30]


In [3]:
print(a+10) # add a value in array
print(a-30) # subs a value in array
print(a*2) # multiply by a value in array
print(a/10) # divide by a value in array

[ 20  30  50 -20]
[-20 -10  10 -60]
[ 20  40  80 -60]
[ 1.  2.  4. -3.]


In [4]:
b=np.array([1,4,9])
print(b)

[1 4 9]


In [5]:
print(np.square(b)) # square of all array elements
print(np.sqrt(b))   # square root of all array elements

[ 1 16 81]
[1. 2. 3.]


In [8]:
print(np.sin(np.pi/2)) #sin
print(np.sin(b))

1.0
[ 0.84147098 -0.7568025   0.41211849]


In [9]:
# 8 Mathematical Operations on Muliple Arrays

In [10]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [11]:
print(np.add(a,b))  # add two arrays
print(np.subtract(a,b))  # subtract two arrays
print(np.multiply(a,b))  # multiply two arrays
print(np.divide(a,b))  # divide two arrays

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [12]:
# Dot product: computes the inner product of the two vectors and sum the results
print(np.dot(a,b))

32


In [13]:
print(a.T) # Transpose: Returns an array with axes transposed

[1 2 3]


In [14]:
t=np.array([[1,2,3],[4,5,6]])
print(t)   # initial shape: 2,3
print(t.T) # shape after transpose: 3,2

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [15]:
# 9 Statistical Functions

In [16]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [17]:
print(np.sum(a)) # sum of all elements of an array

21


In [18]:
print(np.mean(a)) 
print(np.median(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))

3.5
3.5
1.707825127659933
1
6


In [19]:
# 10 Array Comparison

In [21]:
a=np.array([1,5,3])
b=np.array([4,5,6])
print(a)
print(b)

[1 5 3]
[4 5 6]


In [22]:
print(a==b) # comparing each elements of an array
print(np.array_equal(a,b)) # comparing complete array

[False  True False]
False


In [23]:
# 11 Broadcasting

In [24]:
# Broadcasting: is a mechanism that allows arithmetic operations to be performed on arrays of different shapes and sizes,
# it eliminates the need for explicit loops or reshaping operations, making code more concise, readable and efficient.

# Broadcasting Rules:
    # Compare shapes from right to left.
    # Dimensions must match or be 1.
    # If one array has fewer dimensions, pad its shape on the left with 1s.
    # Any dimension equal to 1 can stretch to match the other array.

In [25]:
a=np.array([1,2,3,4])
b=np.array([5])
print(a+b)  # adding 1D with 0ne-element array to 1D with multi-element arra

[6 7 8 9]


In [28]:
c=np.array([[1,2,3],[4,5,6]])
d=np.array([10,20,30])
print(c+d) # adding 2D with 6-element array (2,3) to 1D with 6-element array

[[11 22 33]
 [14 25 36]]


In [29]:
# 12 Handling with nan & inf

In [30]:
data1=np.array([1,2,np.nan,4,np.inf])
print(data1)

[ 1.  2. nan  4. inf]


In [31]:
print(np.isnan(data1)) # check null value and returns boolean value

[False False  True False False]


In [32]:
print(np.nan_to_num(data1)) # replace non-finite values within an array with specified finite numbers

[1.00000000e+000 2.00000000e+000 0.00000000e+000 4.00000000e+000
 1.79769313e+308]


In [33]:
# save and load arrays

In [34]:
arr=np.array([1,0,0,8])
print(arr)
np.save('my_array.npy',arr)

[1 0 0 8]


In [35]:
loaded_arr=np.load('my_array.npy')
print(loaded_arr)

[1 0 0 8]


In [36]:
# Create 5X5 matrix with values from 1 to 25

In [37]:
arr_5=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(arr_5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [38]:
print("Shape",arr_5.shape)

Shape (5, 5)


In [39]:
# extract last row
print(arr_5[-1])

[21 22 23 24 25]


In [41]:
# first column
print(arr_5[::,0])

[ 1  6 11 16 21]


In [50]:
arr_3_1=np.array([1,2,3])
arr_3=np.array([[1],[2],[3]])
print(arr_3_1)
print(arr_3)

[1 2 3]
[[1]
 [2]
 [3]]


In [51]:
print(np.multiply(arr_3_1,arr_3))

[[1 2 3]
 [2 4 6]
 [3 6 9]]
