In [1]:
import numpy as np

In [15]:
#Array fundamentals

In [2]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
print(arr[0])

1


In [6]:
arr[0]=10
print(arr)

[10  2  3  4  5]


In [7]:
print(arr[:3])

[10  2  3]


In [12]:
b=arr[3:]
print(b)
b[0]=40
print(b)
print(arr)

[40  5]
[40  5]
[10  2  3 40  5]


In [13]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
print(a[1,3])

8


In [16]:
#Array attributes
#This section covers the ndim, shape, size, and dtype attributes of an array.

In [18]:
print(a.ndim)

2


In [19]:
print(a.shape)

(3, 4)


In [21]:
print(len(a.shape)==a.ndim)

True


In [22]:
print(a.size)

12


In [23]:
import math

In [24]:
print(a.size==math.prod(a.shape))

True


In [25]:
print(a.dtype)

int64


In [26]:
#How to create a basic array
#This section covers np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

In [27]:
a=np.zeros(2)
print(a)

[0. 0.]


In [28]:
a=np.ones(2)
print(a)

[1. 1.]


In [31]:
# Create an empty array with 2 elements
a=np.empty(2)
print(a)

[1. 1.]


In [32]:
print(np.arange(4))

[0 1 2 3]


In [33]:
print(np.arange(2,9,2))

[2 4 6 8]


In [35]:
print(np.linspace(0,10,num=5))

[ 0.   2.5  5.   7.5 10. ]


In [36]:
x=np.ones(2,dtype=np.int64)
print(x)

[1 1]


In [37]:
#Adding, removing, and sorting elements
#This section covers np.sort(), np.concatenate()

In [38]:
arr=np.array([2,1,5,3,7,4,6,8])
print(arr)

[2 1 5 3 7 4 6 8]


In [41]:
arr1=np.sort(arr)
print(arr)
print(arr1)

[2 1 5 3 7 4 6 8]
[1 2 3 4 5 6 7 8]


In [42]:
arr2=np.concatenate((arr,arr1))
print(arr2)

[2 1 5 3 7 4 6 8 1 2 3 4 5 6 7 8]


In [43]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])
print(np.concatenate((x,y),axis=0))

[[1 2]
 [3 4]
 [5 6]]


In [45]:
#How do you know the shape and size of an array?
#This section covers ndarray.ndim, ndarray.size, ndarray.shape

In [50]:
arr=np.array([
              [ 
                [0,1,2,3],
                [4,5,6,7]
              ],
              [
                [0,1,2,3],
                [4,5,6,7]
              ],
              [
                [0,1,2,3],
                [4,5,6,7]
              ]
            ])
print(arr)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [51]:
print(arr.ndim)

3


In [52]:
print(arr.size)

24


In [53]:
print(arr.shape)

(3, 2, 4)


In [54]:
#Can you reshape an array?
#This section covers arr.reshape()

In [58]:
arr=np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [59]:
arr1=arr.reshape(3,2)
print(arr1)

[[0 1]
 [2 3]
 [4 5]]


In [60]:
print(arr1.reshape(1,6))

[[0 1 2 3 4 5]]


In [61]:
#How to convert a 1D array into a 2D array (how to add a new axis to an array)
#This section covers np.newaxis, np.expand_dims

In [62]:
a=np.array([1,2,3,4,5,6])
print(a)
print(a.shape)

[1 2 3 4 5 6]
(6,)


In [63]:
a2=a[np.newaxis,:]
print(a2)
print(a2.shape)

[[1 2 3 4 5 6]]
(1, 6)


In [65]:
b=a[:,np.newaxis]
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [66]:
b=np.expand_dims(a,axis=1)
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [67]:
#Indexing and slicing

In [68]:
data=np.array([1,2,3])
print(data[1])
print(data[0:2])
print(data[-2:])

2
[1 2]
[2 3]


In [73]:
a=np.array([[1,2,3,10],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3 10]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [74]:
print(a[a<5])

[1 2 3]


In [75]:
five_up=a>=5
print(a[five_up])

[10  5  6  7  8  9 10 11 12]


In [76]:
divisible_by_2=a[a%2==0]
print(divisible_by_2)

[ 2 10  6  8 10 12]


In [77]:
c=a[(a>2) & (a<11)]
print(c)

[ 3 10  5  6  7  8  9 10]


In [79]:
five_up=(a>5) | (a==5)
print(five_up)

[[False False False  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [80]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [82]:
b=np.nonzero(a<5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [84]:
#How to create an array from existing data
#This section covers slicing and indexing, np.vstack(),
#np.hstack(), np.hsplit(), .view(), copy()

In [85]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [86]:
arr=a[3:8]
print(arr)

[4 5 6 7 8]


In [87]:
a1=np.array([[1,1],[2,2]])
a2=np.array([[3,3],[4,4]])
print(a1)
print(a2)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [89]:
#vstack
print(np.vstack((a1,a2)))

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [90]:
#hstack
print(np.hstack((a1,a2)))

[[1 1 3 3]
 [2 2 4 4]]


In [95]:
x=np.arange(1,25).reshape(2,12)
print(x)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [96]:
print(np.hsplit(x,3))

[array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]


In [97]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [101]:
b1=a[0,:]
print(b1)

[1 2 3 4]


In [102]:
b1[0]=99
print(b1)
print(a)

[99  2  3  4]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [104]:
#Basic array operations
#This section covers addition, subtraction, multiplication, division, and more

In [106]:
data=np.array([1,2])
ones=np.ones(2,dtype=np.int_)
print(data)
print(ones)
print(data + ones)

[1 2]
[1 1]
[2 3]


In [107]:
print(data-ones)
print(data*ones)
print(data/ones)

[0 1]
[1 2]
[1. 2.]


In [109]:
a=np.array([1,2,3,4,5])
print(a)
print(a.sum())

[1 2 3 4 5]
15


In [110]:
b=np.array([[1,1],[2,2]])
print(b.sum(axis=0))

[3 3]


In [111]:
print(b.sum(axis=1))

[2 4]


In [113]:
#Broadcasting
#There are times when you might want to carry out an operation
#between an array and a single number or between arrays of two different sizes.

In [115]:
data=np.array([1,2])
print(data*1.6)

[1.6 3.2]


In [116]:
#More useful array operations
#min, max, and sum
#mean,, prod, and std

In [117]:
data=np.array([1,2,3])
print(data.max())
print(data.min())
print(data.sum())

3
1
6


In [119]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
print(a.sum())
print(a.min())

4.8595784
0.05093587


In [121]:
print(a.min(axis=0))

[0.12697628 0.05093587 0.26590556 0.5510652 ]


In [122]:
#Creating matrices

In [123]:
data=np.array([[1,2],[3,4],[5,6]])
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [124]:
print(data[0,1])

2


In [125]:
print(data[1:3])

[[3 4]
 [5 6]]


In [126]:
print(data[0:2,0])

[1 3]


In [128]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [129]:
data=np.array([[1,2],[5,3],[4,6]])
print(data)

[[1 2]
 [5 3]
 [4 6]]


In [131]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 5 6]


In [132]:
print(data.min(axis=0))
print(data.min(axis=1))

[1 2]
[1 3 4]


In [133]:
data=np.array([[1,2],[3,4],[5,6]])
one_row=np.array([[1,1]])
print(data+one_row)

[[2 3]
 [4 5]
 [6 7]]


In [134]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [135]:
np.ones(3)

array([1., 1., 1.])

In [136]:
np.zeros(3)

array([0., 0., 0.])

In [139]:
rng=np.random.default_rng()
rng.random(3)

array([0.58638481, 0.26694372, 0.27853245])

In [140]:
print(np.ones((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [141]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [142]:
rng.random((3,2))

array([[0.80974973, 0.92472067],
       [0.05176235, 0.19647147],
       [0.66272731, 0.69637954]])

In [143]:
#Generating random numbers

In [145]:
rng.integers(5,size=(2,4))

array([[1, 4, 4, 4],
       [0, 3, 1, 1]])

In [146]:
#How to get unique items and counts
#This section covers np.unique()

In [147]:
arr=np.array([11,11,12,12,14,13,14,13,15,15,13,16,16,17])
print(np.unique(arr))

[11 12 13 14 15 16 17]


In [149]:
unique_values, indices_list=np.unique(arr,return_index=True)
print(indices_list)

[ 0  2  5  4  8 11 13]


In [150]:
unique_values, occurrence_count=np.unique(arr,return_counts=True)
print(occurrence_count)

[2 2 3 2 2 2 1]


In [151]:
a_2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[1,2,3,4]])
print(a_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


In [152]:
unqiue_values=np.unique(a_2d)
print(unqiue_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [153]:
unique_rows=np.unique(a_2d,axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [154]:
#Transposing and reshaping a matrix
#This section covers arr.reshape(), arr.transpose(), arr.T

In [155]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [156]:
print(data.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [157]:
print(data.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [158]:
arr=np.arange(6).reshape((2,3))
print(arr)

[[0 1 2]
 [3 4 5]]


In [159]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [160]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [161]:
#How to reverse an array
#This section covers np.flip()

In [162]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr)
print(np.flip(arr))

[1 2 3 4 5 6 7 8]
[8 7 6 5 4 3 2 1]


In [163]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [164]:
print(np.flip(arr_2d))

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [165]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [166]:
print(np.flip(arr_2d,axis=0))

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [167]:
print(np.flip(arr_2d,axis=1))

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [168]:
#Reshaping and flattening multidimensional arrays
#This section covers .flatten(), ravel()

In [170]:
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [172]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [173]:
a1=x.flatten()
a1[0]=99
print(x)
print(a1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


In [174]:
a2=x.ravel()
a2[0]=98
print(x)
print(a2)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]


In [175]:
#How to access the docstring for more information
#This section covers help(), ?, ??

In [176]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more positional arguments, return the largest argument.



In [177]:
a=np.array([1,2,3,4,5,6])
a?

Type:            ndarray
String form:     [1 2 3 4 5 6]
Length:          6
File:            c:\users\ankit gupta\appdata\local\programs\python\python314\lib\site-packages\numpy\__init__.py
Docstring:      
ndarray(shape, dtype=None, buffer=None, offset=0, strides=None, order=None)
--

ndarray(shape, dtype=np.float64, buffer=None, offset=0, strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(fo

In [178]:
#How to save and load NumPy objects
#This section covers np.save, np.savez, np.savetxt, np.load, np.loadtxt

In [179]:
a=np.array([1,2,3,4,5,6])
np.save('filename',a)

In [180]:
b=np.load('filename.npy')
print(b)

[1 2 3 4 5 6]


In [181]:
csv_arr=np.array([1,2,3,4,5,6,7,8])
np.savetxt('new_file.csv',csv_arr)

In [182]:
np.loadtxt('new_file.csv')

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [183]:
#End of the numpy basic